site_name: Oussama — Football Analytics
site_url: https://<your-username>.github.io/portfolio
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
  language: en
nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
      - xG Match Report: projects/xg-report.md
      - Player Similarity: projects/similarity.md
      - Expected Threat (xT): projects/xt.md
      - Set-Pieces: projects/setpieces.md
  - About: about.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/<your-handle>
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>
