site_name: Oussama Osseili — Portfolio
site_url: https://oussamaosseili.github.io/portfolio
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
nav:
  - Home: index.md
  - Software Engineering:
      - Overview: software/index.md
      - Full-Stack App: software/fullstack.md
      - API Design & Testing: software/api-design.md
  - Data & AI:
      - Overview: data/index.md
      - ETL + EDA: data/etl-eda.md
      - ML Mini-Projects: data/ml-mini.md
  - Cloud & DevOps:
      - Overview: devops/index.md
      - Docker & Compose: devops/docker.md
      - CI/CD (GitHub Actions): devops/ci-cd.md
  - ERP & Business:
      - Overview: erp/index.md
      - BPMN & Process Docs: erp/bpmn.md
      - Small ERP Demo: erp/demo.md
  - (Optional) Sports Analytics:
      - Overview: sports/index.md
      - xG / xT Basics: sports/xg-xt.md
  - About: about.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/your-handle
    - icon: fontawesome/brands/github
      link: https://github.com/oussamaosseili
